- name: install the u-a package
  ansible.builtin.package:
    name: unattended-upgrades
  become: yes

- name: Copy IMLS client pi systemd service files
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system
    owner: root
    group: root
    force: yes
  loop:
    - run-imls-client-pi-playbook.service
    - run-imls-client-pi-playbook.timer
    - setup-imls-client-pi-playbook.service
  become: yes
  when: develop is undefined

- name: Copy IMLS client pi systemd service files for dev only
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system
    owner: root
    group: root
    force: yes
  loop:
    - run-imls-client-pi-playbook.service
    - run-imls-client-pi-playbook-dev.timer
    - setup-imls-client-pi-playbook.service
  become: yes
  when: develop is defined

- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: Pull the playbook
  systemd:
    name: setup-imls-client-pi-playbook
    state: started
  become: yes

- name: Start a daily 2am timer to pull the playbook
  systemd:
    name: run-imls-client-pi-playbook.timer
    state: started
  become: yes

- name: enable reboots
  # /etc/apt/apt.conf.d/50unattended-upgrades
  # //Unattended-Upgrade::Automatic-Reboot "false";
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    line: "{{ item }}"
    state: present
  become: yes
  loop:
    - Unattended-Upgrade::Automatic-Reboot-Time "03:00";
    - Unattended-Upgrade::Automatic-Reboot "true";
    - Unattended-Upgrade::Automatic-Reboot-WithUsers "true";
    - Unattended-Upgrade::SyslogEnable "true";

- name: force a reboot at 3am every morning
  ansible.builtin.cron:
    name: "reboot_daily"
    minute: "0"
    hour: "3"
    job: "reboot"
